#!/bin/sh

# exit if any command in the script exits with a code != 0
set -e

# lint + typecheck
npm run lint
npm run typecheck
cd frontend && npm run typecheck && cd ..
cd backend && npm run typecheck && cd ..
