name: tipcards-local-dev

services:
  postgres:
    image: postgres:16.9
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - ./scripts/docker/.postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-data.sh
    ports:
      - 127.0.0.1:5432:5432
