name: tipcards-local-dev

services:
  postgres:
    image: postgres:16.9
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - ./scripts/docker/postgres/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  lnbits-postgres:
    image: postgres:16.9
    container_name: lnbits-postgres
    restart: unless-stopped
    volumes:
      - ./data/lnbits/postgres:/var/lib/postgresql/data
      - ./scripts/docker/lnbits/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "lnbits"
      POSTGRES_PASSWORD: "gobrrrrrr"
      POSTGRES_DB: "lnbits"
    ports:
      - 5433:5432      

  lnbits:
    image: lnbits/lnbits:v1.2.1
    container_name: lnbits
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4050"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s    
    depends_on:
      - lnbits-postgres
    volumes:
      - ./data/lnbits/data:/app/data
      - ./scripts/docker/lnbits/certs/combined.pem:/etc/ssl/certs/combined.pem:ro
    ports:
      - 4050:4050
    env_file:
      - ./scripts/docker/lnbits/.env
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/combined.pem

  proxy:
    image: nginx:stable
    container_name: proxy
    networks:
      default:
        aliases:
          - www.tipcards.internal
          - api.tipcards.internal
          - lnbits.tipcards.internal
    volumes:
      - ./scripts/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts/docker/nginx/certs:/etc/nginx/certs:ro
    ports:
      - 443:443
    depends_on:
      lnbits:
        condition: service_healthy    

  volt-vault-mock:
    image: mockserver/mockserver:5.15.0
    container_name: volt-vault-mock
    networks:
      default:
        aliases:
          - volt-vault.tipcards.internal    
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/config.json
    volumes:
      - ./scripts/docker/volt-vault-mock:/config

networks:
  default:
    name: tipcards-internal
