#!/bin/bash
set -e;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "${POSTGRES_TIPCARDS_USER}" WITH PASSWORD '${POSTGRES_TIPCARDS_PASSWORD}';
  CREATE DATABASE "${POSTGRES_TIPCARDS_DATABASE}";
  GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_TIPCARDS_DATABASE}" TO "${POSTGRES_TIPCARDS_USER}";
  \c "${POSTGRES_TIPCARDS_DATABASE}" "${POSTGRES_USER}"
  GRANT ALL ON SCHEMA public TO "${POSTGRES_TIPCARDS_USER}";
EOSQL
