<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xml:space="preserve"
    shape-rendering="geometricPrecision"
    text-rendering="geometricPrecision"
    image-rendering="optimizeQuality"
    fill-rule="evenodd"
    clip-rule="evenodd"
    viewBox="0 0 16.8 16.1"
  >
    <line
      x1="1.5"
      y1="1.5"
      x2="15.3"
      y2="14.6"
      stroke="currentColor"
      stroke-width="3"
    />
    <line
      x1="1.5"
      y1="14.6"
      x2="15.3"
      y2="1.5"
      stroke="currentColor"
      stroke-width="3"
    />
  </svg>
</template>
