import { pgTable, varchar, timestamp, json } from 'drizzle-orm/pg-core'

export const User = pgTable('User', {
  id: varchar('id', { length: 64 }).primaryKey().unique().notNull(), // Note: sha256 of foreign id or uuid
  lnurlAuthKey: varchar('lnurlAuthKey', { length: 128 }).notNull(), // Note: signed sha256 generated by lightning wallet
  created: timestamp('created', { mode: 'date', withTimezone: true }).notNull(),
  permissions: json('permissions').notNull(), // Note: make array if database supports it: permissions[], otherwise json
})

export type User = typeof User.$inferSelect
