#!/bin/bash
set -e;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "${POSTGRES_NON_ROOT_PROJECT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PROJECT_USER_PASSWORD}';
  CREATE DATABASE "${POSTGRES_PROJECT_DATABASE}";
  GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_PROJECT_DATABASE}" TO "${POSTGRES_NON_ROOT_PROJECT_USER}";
  \c "${POSTGRES_PROJECT_DATABASE}" "${POSTGRES_USER}"
  GRANT ALL ON SCHEMA public TO "${POSTGRES_NON_ROOT_PROJECT_USER}";
EOSQL
