import { mysqlTable, varchar, datetime, json } from 'drizzle-orm/mysql-core'
import z from 'zod'

const PERMISSIONS = [
  'statistics', // Note: allow read access to https://tipcards.io/statistics
  'support', // Note: allow access to the support dashboard
] as const

export const Permissions = z.enum(PERMISSIONS)

export type Permissions = z.infer<typeof Permissions>


export const User = mysqlTable('User', {
  id: varchar('id', { length: 36 }).primaryKey().unique().notNull(), // Note: uuid
  lnurlAuthKey: varchar('lnurlAuthKey', { length: 128 }).notNull(), // Note: signed sha256 generated by lightning wallet
  created: datetime('created').notNull(),
  permissions: json('permissions').notNull(), // Note: make array if database supports it: permissions[], otherwise json
})

export type User = typeof User.$inferSelect
