import { mysqlTable, varchar, datetime, json } from 'drizzle-orm/mysql-core'

export const User = mysqlTable('User', {
  id: varchar('id', { length: 64 }).primaryKey().unique().notNull(), // Note: sha256 of foreign id or uuid
  lnurlAuthKey: varchar('lnurlAuthKey', { length: 128 }).notNull(), // Note: signed sha256 generated by lightning wallet
  created: datetime('created').notNull(),
  permissions: json('permissions').notNull(), // Note: make array if database supports it: permissions[], otherwise json
})

export type User = typeof User.$inferSelect
