import { mysqlTable, varchar, datetime, mysqlEnum } from 'drizzle-orm/mysql-core'

const permissions: [string, ...string[]] = [
  'statistics', // Note: allow read access to https://tipcards.io/statistics
  'support', // Note: allow access to the support dashboard
]

export const User = mysqlTable('User', {
  id: varchar('id', { length: 36 }).primaryKey().unique().notNull(), // Note: uuid
  lnurlAuthKey: varchar('lnurlAuthKey', { length: 128 }).notNull(), // Note: signed sha256 generated by lightning wallet
  created: datetime('created').notNull(),
  permissions: mysqlEnum('permissions', permissions).notNull(), // Note: make array if database supports it: permissions[], otherwise json
})

export type User = typeof User.$inferSelect
