export enum AuthErrorCodes {
  HOST_MISSING = 'HOST_NOT_SET',
  ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  REFRESH_TOKEN_DENIED = 'REFRESH_TOKEN_DENIED',
}
