let API_ORIGIN = process.env.TIPCARDS_API_ORIGIN || ''
if (process.env.API_ORIGIN_INTEGRATION) {
  API_ORIGIN = process.env.API_ORIGIN_INTEGRATION
}

let AUTH_ORIGIN = API_ORIGIN || ''
if (process.env.AUTH_ORIGIN_INTEGRATION) {
  AUTH_ORIGIN = process.env.AUTH_ORIGIN_INTEGRATION
}

let LNBITS_ORIGIN_INTEGRATION = process.env.LNBITS_ORIGIN || ''
if (process.env.LNBITS_ORIGIN_INTEGRATION) {
  LNBITS_ORIGIN_INTEGRATION = process.env.LNBITS_ORIGIN_INTEGRATION
}

let LNBITS_ADMIN_KEY_TEST_USER_WALLET = process.env.LNBITS_ADMIN_KEY || ''
if (process.env.LNBITS_ADMIN_KEY_TEST_USER_WALLET) {
  LNBITS_ADMIN_KEY_TEST_USER_WALLET = process.env.LNBITS_ADMIN_KEY_TEST_USER_WALLET
}

export {
  API_ORIGIN,
  AUTH_ORIGIN,
  LNBITS_ORIGIN_INTEGRATION,
  LNBITS_ADMIN_KEY_TEST_USER_WALLET,
}
