let API_ORIGIN = process.env.TIPCARDS_API_ORIGIN || ''
if (process.env.TEST_API_ORIGIN) {
  API_ORIGIN = process.env.TEST_API_ORIGIN
}

let WALLET_LNBITS_ORIGIN = process.env.LNBITS_ORIGIN || ''
if (process.env.TEST_WALLET_LNBITS_ORIGIN) {
  WALLET_LNBITS_ORIGIN = process.env.TEST_WALLET_LNBITS_ORIGIN
}

let WALLET_LNBITS_ADMIN_KEY = process.env.LNBITS_ADMIN_KEY || ''
if (process.env.TEST_WALLET_LNBITS_ADMIN_KEY) {
  WALLET_LNBITS_ADMIN_KEY = process.env.TEST_WALLET_LNBITS_ADMIN_KEY
}

export {
  API_ORIGIN,
  WALLET_LNBITS_ORIGIN,
  WALLET_LNBITS_ADMIN_KEY,
}
