test-backend-integration:
  stage: integration-and-e2e
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27.5.1
  tags:
    - docker
  services:
    - docker:27.5.1-dind
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, web_and_push]
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  variables:
    CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}
    NODE_ENV: test
  before_script:
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login $CI_DEPENDENCY_PROXY_SERVER -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - docker compose --profile tools --profile test up -d --wait
  script:
    - ./scripts/docker/run-backend-integration.sh
  after_script:
    - |
      echo "Job status was: $CI_JOB_STATUS"
      if [ "${CI_JOB_STATUS:-success}" != "success" ]; then
        echo "Dumping backend logs:"
        docker logs tipcards-backend-test || true
      fi
    - docker compose --profile tools --profile test down

test-e2e-cypress:
  stage: integration-and-e2e
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27.5.1
  tags:
    - docker
  services:
    - docker:27.5.1-dind
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, web_and_push]
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  variables:
    CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}
    NODE_ENV: test
  before_script:
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login $CI_DEPENDENCY_PROXY_SERVER -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - docker compose --profile tools --profile test up -d --wait
  script:
    - |
      docker run --rm \
        --network=tipcards-localhost \
        -v $(pwd):/app \
        -w /app \
        -e NODE_EXTRA_CA_CERTS=/app/scripts/docker/nginx/certs/rootCA.pem \
        cypress/browsers:node-20.15.1-chrome-126.0.6478.114-1-ff-128.0-edge-126.0.2592.61-1 /bin/bash \
        -c "apt-get update && apt-get install -y xsel && npx cypress install && npm run e2e:cypress:tests"
  after_script:
    - |
      echo "Job status was: $CI_JOB_STATUS"
      if [ "${CI_JOB_STATUS:-success}" != "success" ]; then
        echo "Dumping backend logs:"
        docker logs tipcards-backend-test || true
        echo "Dumping frontend logs:"
        docker logs tipcards-frontend-test || true
      fi
    - docker compose --profile tools --profile test down

test-e2e-playwright:
  stage: integration-and-e2e
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27.5.1
  tags:
    - docker
  services:
    - docker:27.5.1-dind
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, web_and_push]
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  variables:
    CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}
    NODE_ENV: test
  artifacts:
    name: playwright-e2e
    when: always
    paths:
      - playwright-report
    expire_in: 1 day
  before_script:
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login $CI_DEPENDENCY_PROXY_SERVER -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - docker compose --profile tools --profile test up -d --wait
  script:
    - |
      docker run --rm \
        --network=tipcards-localhost \
        -v $(pwd):/app \
        -w /app \
        -e NODE_EXTRA_CA_CERTS=/app/scripts/docker/nginx/certs/rootCA.pem \
        node:lts-bookworm-slim /bin/bash \
        -c "npx playwright install --with-deps && npm run e2e:playwright:tests"
  after_script:
    - |
      echo "Job status was: $CI_JOB_STATUS"
      if [ "${CI_JOB_STATUS:-success}" != "success" ]; then
        echo "Dumping backend logs:"
        docker logs tipcards-backend-test || true
        echo "Dumping frontend logs:"
        docker logs tipcards-frontend-test || true
      fi
    - docker compose --profile tools --profile test down
