test-backend-integration:
  stage: integration-and-e2e
  image: docker:27.5.1
  tags:
    - docker
  services:
    - docker:27.5.1-dind
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, web_and_push]
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  variables:
    NODE_ENV: test
  before_script:
    - docker compose --profile tools --profile test up -d --wait
  script:
    - ls -al
    - ./scripts/docker/run-backend-integration.sh
  after_script:
    - |
      echo "Job status was: $CI_JOB_STATUS"
      if [ "${CI_JOB_STATUS:-success}" != "success" ]; then
        echo "Dumping backend logs:"
        docker logs tipcards-backend-test || true
      fi
    - docker compose --profile tools --profile test down

test-e2e:
  stage: integration-and-e2e
  image: docker:27.5.1
  tags:
    - docker
  services:
    - docker:27.5.1-dind
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, web_and_push]
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  variables:
    NODE_ENV: test
  artifacts:
    name: cypress-e2e
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
  before_script:
    - docker compose --profile tools --profile test up -d --wait
  script:
    - |
      docker run --rm \
        --network=tipcards-localhost \
        -v $(pwd):/app \
        -w /app \
        -e NODE_EXTRA_CA_CERTS=/app/scripts/docker/nginx/certs/rootCA.pem \
        cypress/browsers:node-20.15.1-chrome-126.0.6478.114-1-ff-128.0-edge-126.0.2592.61-1 /bin/bash \
        -c "apt-get update && apt-get install -y xsel && npx cypress install && npm run e2e-tests"
  after_script:
    - |
      echo "Job status was: $CI_JOB_STATUS"
      if [ "${CI_JOB_STATUS:-success}" != "success" ]; then
        echo "Dumping backend logs:"
        docker logs tipcards-backend-test || true
        echo "Dumping frontend logs:"
        docker logs tipcards-frontend-test || true
      fi
    - docker compose --profile tools --profile test down
