# This job will run even if the previous stages fail.
# It tests the live environment, which should always be available.
live-check:
  image: cypress/browsers:node-20.15.1-chrome-126.0.6478.114-1-ff-128.0-edge-126.0.2592.61-1
  stage: live-check
  rules:
    - !reference [.shared_config, rules, no_tags]
    - !reference [.shared_config, rules, deployable_branches]
    - !reference [.shared_config, rules, web_and_push_and_schedule]
    - !reference [.shared_config, rules, nightly_integration]
    - when: always # even run when previous stages fail
  cache:
    - !reference [.shared_config, cache, node_modules]
  variables:
    NODE_ENV: test
  artifacts:
    name: cypress-live-check
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day    
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        cp $E2E_ENV_FILE_LIVE_CHECK_MAIN e2e/.env.local
      elif [ "$CI_COMMIT_BRANCH" == "develop" ]; then
        echo "Running on develop branch"
        cp $E2E_ENV_FILE_LIVE_CHECK_DEVELOP e2e/.env.local
      else
        echo "ERROR: this branch $CI_COMMIT_BRANCH is not allowed to run this job! Wake up your devops team!"
        exit 1
      fi
    - echo "Installing cypress"
    - npx cypress install
    - echo "Running e2e-live-checks on branch $CI_COMMIT_BRANCH"
    - npm run e2e-live-checks
